# Generated by Django 6.0 on 2026-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cheque_no', models.BigIntegerField()),
                ('payer', models.TextField()),
                ('payee', models.TextField()),
                ('amount', models.FloatField()),
                ('issue_date', models.DateTimeField()),
                ('post_date', models.DateField()),
                ('status', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
