# Generated by Django 6.0 on 2026-04-10 05:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(max_length=20)),
                ('payee', models.TextField()),
                ('amount', models.FloatField()),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='cheques/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('payee', models.CharField(max_length=255)),
                ('cheque_date', models.DateField()),
                ('alert_type', models.CharField(default='GENERAL', max_length=20)),
                ('alerts', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheque.cheque')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.UniqueConstraint(fields=('user', 'cheque_no'), name='unique_user_cheque'),
        ),
    ]
