# Generated by Django 6.0 on 2026-02-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0002_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='Image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
