# Generated by Django 6.0 on 2026-03-18 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0002_alter_alerts_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='cheque',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cheque.cheque'),
            preserve_default=False,
        ),
    ]
