# Generated by Django 6.0 on 2026-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0002_alter_cheque_description_alter_cheque_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cheque_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
