# Generated by Django 6.0 on 2026-03-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0003_cheque_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='payer',
        ),
        migrations.AlterField(
            model_name='cheque',
            name='post_date',
            field=models.DateField(default='null'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
