# Generated by Django 6.0 on 2026-03-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0003_alerts_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20),
        ),
    ]
