# Generated by Django 6.0 on 2026-03-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0004_remove_cheque_payer_alter_cheque_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
