# Generated by Django 6.0 on 2026-03-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0004_alter_cheque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='alert_type',
            field=models.CharField(default='GENERAL', max_length=20),
        ),
    ]
