# Generated by Django 6.0 on 2026-03-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0005_alter_cheque_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='user_id',
            field=models.CharField(),
        ),
    ]
