# Generated by Django 6.0 on 2026-04-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0005_alerts_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='Image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
