# Generated by Django 6.0 on 2026-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0006_alter_cheque_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/'),
        ),
    ]
