# Generated by Django 6.0 on 2026-03-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0006_alter_cheque_description_alter_cheque_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
