# Generated by Django 6.0 on 2026-03-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0007_alter_cheque_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
