# Generated by Django 6.0 on 2026-04-06 04:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0007_alter_cheque_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='Image',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
