# Generated by Django 6.0 on 2026-04-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0008_alter_cheque_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='Image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
