# Generated by Django 6.0 on 2026-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0008_alter_cheque_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='cheque',
            name='Image',
            field=models.ImageField(upload_to='cheques/'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='payee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
