# Generated by Django 6.0 on 2026-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0009_alter_cheque_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='cheque_no',
            field=models.CharField(unique=True),
        ),
    ]
