# Generated by Django 6.0 on 2026-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0010_alter_cheque_cheque_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/'),
        ),
    ]
