# Generated by Django 6.0 on 2026-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobilenumber',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
