# Generated by Django 6.0 on 2026-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobilenumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
