# Generated by Django 6.0 on 2026-04-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cheque_requested',
            field=models.BooleanField(default=False),
        ),
    ]
